---
title: "Lab 1"
format: gfm
editor: source
---

### Q1. Prior Distributions (4 pts)

Summarize a prior distribution in a way that someone with a minimal statistical background, such as a parent or sibling, could understand. 

Note that while you are taking a statistics class, writing, and speaking, will be essential to how we convey our results. Please use proper grammar, sentence structure, and complete paragraphs.


### Q2. Beta Distribution

#### a. (2 pts) 
Write out probability distribution for a beta distribution. Hint, you can use LaTex...


#### b. (4 pts) 
Using `ggplot2` and `rbeta()` or `dbeta()` investigate the impact of $\alpha$ and $\beta$ on the shape of the resultant probability distribution function. In particular, create or overlay at least 4 different curves that correspond to alternative specifications of $\alpha$ and $\beta$.



#### c. (4 pts)

Building on Q2b, summarize how $\alpha/ (\alpha + \beta)$ and $\alpha + \beta$ change the shape of the probability distribution.


### Q3. Winter Temperature

On Tuesday we considered waiting time for the sunnyside lift on Saturday mornings at Bridger Bowl. Suppose you found the wait times to be too long for your liking. Now let's consider estimating the temperature at Hyalite Canyon (at the reservoir) at 10 AM on Saturdays in February.

We will outline the first three steps of a Bayesian inference:

#### a. (4 pts) Identify the data relevant to the research question. 

Specifically, describe how you design a data collection process to answer the research question (What are the range of expected temperatures at Hyalite Reservoir on Saturdays in February?).


#### b. (4 pts) Identify a descriptive statistical model for the relevant data. Then interpret the statistical parameters in that model.


#### c. (4 pts) Specify a prior distribution for all parameters in the model.
Plot your distribution using ggplot2 and state the parameters in that model. Note you may have multiple parameters that require prior distributions.


### Q4. Optional (ungraded)

This class will have one project that spans the entire course. Recall you are allowed to work in groups of up to size 2 for this project. If you have any remaining course time, give some thought to identifying a dataset that is interesting to you along with an associated research question. 

The project will be scaffolded over the course of the semester and all necessary statistical tools (such as regression) will be taught in this class.

